---
sudo: required
language: python

env:
  - suite: default
    dist: focal
  - suite: default-nosyslog
    dist: focal
  - suite: default
    dist: xenial
  - suite: default-nosyslog
    dist: xenial

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
  - "[ -f get-dependencies.sh ] && sh -x get-dependencies.sh"
  # for local travis execution as we use same default.yml than kitchen
  - mkdir /tmp/kitchen
install:
  - pip install ansible ansible-lint
  - ansible --version
  - "{ echo '[defaults]'; echo 'callback_whitelist = profile_tasks, timer'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - "echo \"localhost\" > inventory"

  # Check the role/playbook's syntax.
  - "ansible-lint tasks/main.yml"
  - "ansible-playbook -i inventory --syntax-check test/integration/${suite}/default.yml -vvvv"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i inventory --connection=local --become -vvvv test/integration/${suite}/default.yml"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - "ansible-playbook -i inventory test/integration/${suite}/default.yml --connection=local --become | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 1)"

after_script:
  - sudo ls /etc/audit/rules.d
  - sudo cat /etc/audit/audit.rules
  - sudo auditctl -l
  - cat /etc/rsyslog.d/30-audisp.conf
  - sudo cat /etc/audisp/plugins.d/syslog.conf
  - sudo tail -100 /var/log/audit/audit.log
