---

- name: Ensure logrotate package is present
  ansible.builtin.package:
    name: logrotate
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Add logrotate configuration for audispd log
  ansible.builtin.template:
    src: logrotate-audispd.j2
    dest: /etc/logrotate.d/audispd
    mode: '0644'
    validate: 'logrotate -dv %s'
