---

- name: augenrules - debian
  command: augenrules
  when: augenrules_file.stat.exists

- name: restart auditd
  service:
    name: auditd
    state: restarted
  when:
    - not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
        )
    - not (ansible_os_family == "RedHat" and ansible_distribution_version.split('.')[0]|int >= 7)

## https://groups.google.com/forum/#!topic/ansible-project/pv1h1Ne7nSk
- name: restart auditd - rhel7
  command: "service auditd restart"
  environment:
    PATH: '/usr/sbin:/usr/bin:/sbin:/bin'
  args:
    warn: False
  when:
    - not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
        )
    - ansible_os_family == "RedHat" and ansible_distribution_version.split('.')[0]|int >= 7
